-- MySQL Script generated by MySQL Workbench
-- Fri Feb  3 00:14:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `USUARIO_id` INT NOT NULL,
  `USUARIO_NOME` VARCHAR(45) NOT NULL,
  `USUARIO_EMAIL` VARCHAR(45) NOT NULL,
  `USUARIO_SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USUARIO_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receita` (
  `RECEITA_ID` INT NOT NULL,
  `RECEITA_NOME` VARCHAR(45) NOT NULL,
  `RECEITA_DESCRICAO` VARCHAR(1000) NOT NULL,
  `RECEITA_INGREDIENTES` VARCHAR(45) NOT NULL,
  `RECEITA_PREPARO` VARCHAR(1000) NOT NULL,
  `usuario_USUARIO_id` INT NOT NULL,
  PRIMARY KEY (`RECEITA_ID`),
  INDEX `fk_receita_usuario_idx` (`usuario_USUARIO_id` ASC) VISIBLE,
  CONSTRAINT `fk_receita_usuario`
    FOREIGN KEY (`usuario_USUARIO_id`)
    REFERENCES `mydb`.`usuario` (`USUARIO_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
